console.log("=== base64 ===")
let b64 = encoding.base64Encode("Hello, R2Lang!")
console.log("encoded: " + b64)
console.log("decoded: " + encoding.base64Decode(b64))

console.log("\n=== base64 url-safe ===")
let b64u = encoding.base64UrlEncode("Hello, R2Lang!?/")
console.log("encoded: " + b64u)
console.log("decoded: " + encoding.base64UrlDecode(b64u))

console.log("\n=== hex ===")
let hx = encoding.hexEncode("R2Lang")
console.log("encoded: " + hx)
console.log("decoded: " + encoding.hexDecode(hx))

console.log("\n=== url query ===")
let qs = encoding.urlEncode("hello world & r2lang=fun")
console.log("encoded: " + qs)
console.log("decoded: " + encoding.urlDecode(qs))

console.log("\n=== url parse ===")
let parsed = encoding.urlParse("https://example.com/path/to/thing?foo=bar&lang=r2")
console.log("scheme: " + parsed.scheme)
console.log("host: " + parsed.host)
console.log("path: " + parsed.path)
console.log("query.foo: " + parsed.query.foo)
console.log("query.lang: " + parsed.query.lang)

console.log("\n=== uuid ===")
let id1 = uuid.v4()
let id2 = uuid.v4()
let id3 = uuid.v4()
console.log("uuid 1: " + id1)
console.log("uuid 2: " + id2)
console.log("uuid 3: " + id3)
console.log("id1 valid: " + uuid.isValid(id1))
console.log("id1 != id2: " + (id1 != id2))
console.log("garbage valid: " + uuid.isValid("not-a-uuid"))
